# Generated by Django 6.0.5 on 2026-05-08 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'Dell'), ('LENOVO', 'Lenovo'), ('APPLE', 'Apple'), ('OTHER', 'Other')], max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_laptops', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_laptops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
