# Generated by Django 6.0.5 on 2026-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_qr/'),
        ),
    ]
