# Generated by Django 6.0.5 on 2026-05-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_laptop_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='is_inside_library',
            field=models.BooleanField(default=False),
        ),
    ]
