# Generated by Django 6.0.5 on 2026-05-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_laptop_is_inside_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
